# Generated by Django 4.2.3 on 2023-07-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexcardsitem',
            old_name='english_text',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='indexcardsitem',
            old_name='german_text',
            new_name='german',
        ),
    ]
